name: Build Python and Release Executable

on:
  push:
    branches: main

permissions:
  contents: write
  pull-requests: write

jobs:
  build-windows-installer:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run PyInstaller
        run: |
          python -m PyInstaller main.spec
      - uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: dist/main/
          
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple
      - name: Upload Release Artifact
        uses: xresloader/upload-to-github-release@v1.6.0
        with:
          file: dist/main/
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true

          

