name: Build Python and Release Executable

on:
  push:
    branches: main

jobs:
  build-windows-installer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run PyInstaller
        run: |
          python -m PyInstaller main.spec
      - uses: actions/upload-artifact@v4
        with:
          name: Windows_Bethpage_Golf_Reservation
          path: dist/main/main
          
      - name: Create/Update Github Release
      # You may pin to the exact commit or the version.
      # uses: mini-bomba/create-github-release@0fd8b05c541176dd92b066cbd0913916ccce1b07
        uses: mini-bomba/create-github-release@v1.1.3
        with:
          # Token used for creating/editing releases
          token: ${{ secrets.GITHUB_TOKEN }}
          # Tag to create/move and use for the release
          tag: ${{ github.event.head_commit.message }}
          # Should the release be marked as a draft?
          draft: false
          # Name of the release
          name: ${{ github.event.head_commit.message }}
          # Body of the release
          body: New version
          # Files to attach; newline seperated, recursive globbing supported
          files: |
            dist/main/main
          # Should the action fail if none of the file globs match?
          fail_on_no_files: true
          

