name: Build Python and Release Executable

on:
  push:
    branches: main

permissions:
  contents: write
  pull-requests: write

jobs:
  build-windows-installer:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run PyInstaller
        run: |
          python -m PyInstaller main.spec
      - name: Zip artifact for deployment
        run: powershell Compress-Archive dist/main release.zip 
      - uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: release.zip
      - name: Upload Release Artifact
        uses: Vucko130/upload-release-action@2.5.4
        with:
          file: release.zip
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: true
          release_name: test
          body: testing


          

